// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gcpyrsiidhkymqtqtflk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdjcHlyc2lpZGhreW1xdHF0ZmxrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwMzI1NzYsImV4cCI6MjA1OTYwODU3Nn0.7XStWLb3MtLzdk3Y3y44hNns7OHHYgBLSmYH9ZOALMI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);